force-app/main/default/objects/CustomProduct__c/CustomProduct__c.object-meta.xml
<CustomObject>
    <label>CustomProduct</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomProduct__c/fields/brand__c.field-meta.xml
<CustomField>
    <fullName>brand__c</fullName>
    <description>the brand name of the shoe manufacturer</description>
    <label>brand</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomProduct__c/fields/category__c.field-meta.xml
<CustomField>
    <fullName>category__c</fullName>
    <label>category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>hiking</fullName>
            </value>
            <value>
                <fullName>indoor</fullName>
            </value>
            <value>
                <fullName>outdoor</fullName>
            </value>
            <value>
                <fullName>running</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomProduct__c/fields/color__c.field-meta.xml
<CustomField>
    <fullName>color__c</fullName>
    <label>color</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomProduct__c/fields/gender__c.field-meta.xml
<CustomField>
    <fullName>gender__c</fullName>
    <label>gender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>mens</fullName>
            </value>
            <value>
                <fullName>womens</fullName>
            </value>
            <value>
                <fullName>boys</fullName>
            </value>
            <value>
                <fullName>girls</fullName>
            </value>
            <value>
                <fullName>unisex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomProduct__c/fields/heel_height__c.field-meta.xml
<CustomField>
    <fullName>heel_height__c</fullName>
    <label>heel height</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomProduct__c/fields/size__c.field-meta.xml
<CustomField>
    <fullName>size__c</fullName>
    <label>size</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1.0</fullName>
            </value>
            <value>
                <fullName>1.5</fullName>
            </value>
            <value>
                <fullName>2.0</fullName>
            </value>
            <value>
                <fullName>2.5</fullName>
            </value>
            <value>
                <fullName>3.0</fullName>
            </value>
            <value>
                <fullName>3.5</fullName>
            </value>
            <value>
                <fullName>4.0</fullName>
            </value>
            <value>
                <fullName>4.5</fullName>
            </value>
            <value>
                <fullName>5.0</fullName>
            </value>
            <value>
                <fullName>5.5</fullName>
            </value>
            <value>
                <fullName>6.0</fullName>
            </value>
            <value>
                <fullName>6.5</fullName>
            </value>
            <value>
                <fullName>7.0</fullName>
            </value>
            <value>
                <fullName>7.5</fullName>
            </value>
            <value>
                <fullName>8.0</fullName>
            </value>
            <value>
                <fullName>8.5</fullName>
            </value>
            <value>
                <fullName>9.0</fullName>
            </value>
            <value>
                <fullName>9.5</fullName>
            </value>
            <value>
                <fullName>10.0</fullName>
            </value>
            <value>
                <fullName>10.5</fullName>
            </value>
            <value>
                <fullName>11.0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomProduct__c/fields/width__c.field-meta.xml
<CustomField>
    <fullName>width__c</fullName>
    <label>width</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>medium</fullName>
            </value>
            <value>
                <fullName>wide</fullName>
            </value>
            <value>
                <fullName>extra wide</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductController.cls
public class ProductController {
    static Integer PAGE_SIZE = 100;
    public class Filters {
        @AuraEnabled
        public String searchKey {get; set;}
        @AuraEnabled
        public Decimal maxPrice {get; set;}
        @AuraEnabled
        public Decimal size {get; set;}
        @AuraEnabled
        public Decimal heelHeight {get; set;}
        @AuraEnabled
        public String category {get; set;}
        @AuraEnabled
        public String[] brand {get; set;}
        @AuraEnabled
        public String color {get; set;}
        @AuraEnabled
        public String width {get; set;}
        @AuraEnabled
        public String gender {get; set;}
    }

    @AuraEnabled(Cacheable=true)
    public static PagedResult getProducts(Filters filters) {
        Integer pageNumber = 1;
        String key, whereClause = '';
        Decimal maxPrice, size, heelHeight;
        String category, color, width, gender;
        String[] criteria, brand = new List<String>{};
        if(filters != null) {
            system.debug(filters);
            maxPrice = filters.maxPrice;
			size = filters.size;
            heelHeight = filters.heelHeight;
            brand = filters.brand;
            color = filters.color;
            width = filters.width;
            gender = filters.gender;
            if (!String.isEmpty(filters.searchKey)) {
                key = '%' + filters.searchKey + '%';
                criteria.add('Name LIKE :key');
            }
            if (filters.maxPrice >= 0) {
                maxPrice = filters.maxPrice;
                criteria.add('price__c <= :maxPrice');
            }
            if (filters.size >= 0) {
                size = filters.size;
                criteria.add('size__c <= :size');
            }
            if (filters.heelHeight >= 0) {
                heelHeight = filters.heelHeight;
                criteria.add('heel_height__c <= :heelHeight');
            }
            if (!String.isEmpty(filters.category)){
                key = '%' + filters.category + '%';
                criteria.add('category__c LIKE :key');
            }
            if (filters.brand != null){
                brand = filters.brand;
                criteria.add('brand__c IN :brand');
            }
            if (!String.isEmpty(filters.color)){
                key = '%' + filters.color + '%';
                criteria.add('color__c LIKE :key');
            }
            if (!String.isEmpty(filters.width)){
                key = '%' + filters.width + '%';
                criteria.add('width__c LIKE :key');
            }
            if (!String.isEmpty(filters.gender)){
                key = '%' + filters.gender + '%';
                criteria.add('gender__c LIKE :key');
            }
            system.debug(String.join(criteria, 'AND '));
            if (criteria.size() > 0) {
                whereClause = 'WHERE ' + String.join(criteria, ' AND ');
            }
        }
        
        Integer pageSize = ProductController.PAGE_SIZE;
        Integer offset = (pageNumber - 1) * pageSize; 
        PagedResult result = new PagedResult();
        result.totalItemCount = Database.countQuery(
            'SELECT count() FROM CustomProduct__c ' + whereClause
        );
        result.records = Database.query(
        	'SELECT Id, Name FROM CustomProduct__c ' +
            whereClause +
            ' WITH SECURITY_ENFORCED' +
            ' ORDER BY Name LIMIT :pageSize OFFSET :offset'
        );
        
        return result;
    } 
}